pub mod columnar;
pub mod column_chunk;
pub mod compression;
pub mod ecc;
pub mod encoding;
pub mod encryption;
pub mod error;
pub mod file_header;
pub mod file_footer;
pub mod integrity;
pub mod row_group;
pub mod reader;
pub mod schema;
pub mod writer;

pub use error::{Error, Result};
pub use column_chunk::{ChunkEncryptionMetadata, ColumnChunkHeader};
pub use file_header::FileHeader;
pub use file_footer::{decode_footer_body, decode_footer_envelope, encode_footer_envelope, FooterContent, FooterRowGroupEntry};
pub use row_group::RowGroupHeader;
pub use writer::StreamingWriter;
pub use reader::FileReader;
pub use schema::{Schema, SchemaBuilder, SchemaField, SchemaMetadataEntry, LogicalTypeId, Nullability, EncodingHint, CompressionHint, EncryptionId};
pub use encoding::{EncodingId, encode as encoding_encode, decode as encoding_decode};
pub use compression::{CompressionId, compress as codec_compress, decompress as codec_decompress, adaptive_select};
pub use encryption::{Cipher, encrypt as aes_encrypt, decrypt as aes_decrypt};
pub use ecc::EccConfig;
pub use columnar::{transpose, untranspose};
