//! Generated compression roundtrip tests.
//!
//! Tests are generated by build.rs covering all 3 compression codecs
//! across 2 input-size levels × 256 byte values = 1,536 test cases.
//!
//! Codecs covered: NONE, ZSTD, LZ4

include!(concat!(env!("OUT_DIR"), "/compression_generated.rs"));
