//! Generated encoding roundtrip tests.
//!
//! Tests are generated by build.rs covering all 7 encoding algorithms
//! across 5 input-size levels × 256 byte values = 8,960 test cases.
//!
//! Algorithms covered:
//!   PLAIN, RLE, BIT_PACKED, DELTA_BINARY, DELTA_BYTE_ARRAY,
//!   BYTE_STREAM_SPLIT, DICTIONARY_RLE

include!(concat!(env!("OUT_DIR"), "/encoding_generated.rs"));
