//! Generated AES-256-GCM encryption roundtrip tests.
//!
//! Tests are generated by build.rs: 256 tests, one per master-key byte
//! variant (key = [n; 32] for n in 0..=255).

include!(concat!(env!("OUT_DIR"), "/encryption_generated.rs"));
