//! Generated CRC32 integrity tests.
//!
//! Tests are generated by build.rs: 256 tests, one per byte value (0–255),
//! verifying crc32_bytes + crc32_matches correctness.

include!(concat!(env!("OUT_DIR"), "/integrity_generated.rs"));
